#pragma once
#include <cstdio>
#include <iostream>
#include <algorithm>
#include <string>
#include <string.h>
//#include "dynamic.h"
#include "fileReader.h"
#include "SplitSentence.h"
#include "struct.h"
#include "print.h"
#include "Utils.h"
